# Generated by Django 2.2.4 on 2020-06-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitforever', '0002_cart_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='different_address',
            name='order_id',
            field=models.IntegerField(default=0),
        ),
    ]
