# Generated by Django 2.2.4 on 2020-06-14 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitforever', '0005_order_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='discount',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='fitforever.Discount'),
        ),
    ]
