# Generated by Django 2.2.4 on 2020-09-27 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitforever', '0008_auto_20200927_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
    ]
