# Generated by Django 2.2.4 on 2020-10-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitforever', '0014_auto_20200927_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='user',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
